### ISSUE TITLE
no report file path was return by the Sweetviz tool

### ISSUE THREAD

**Issue by wildrewwildrew** [business-science/ai-data-science-team#52]
Hi

Can you help with this error:

Sweetviz Report

No report file path was returned by the Sweetviz tool

**Comment by Liam-Sutcliffe** [comment]
I'm also receiving this error, all modules are installed locally. Have tried in docker as well to omit for platform related issues and get the same results.

**Comment by mdancho84** [comment]
On break at the moment. But will look into once I get back. 

In the meantime check out what the function is doing- it's storing the sweetviz report as a temp file. 

This is relatively new. I don't store it in the local directory. 

Also if you could share a complete error report or screenshot of what is happening. That would help. I need to try to reproduce it. And just saying it isn't working is insufficient. 

Give me as much information as you can to try to solve it.

**Comment by Liam-Sutcliffe** [comment]
Process:
I upload the example churn data to the application, enter my API key then enter the following prompt "make a sweetviz report based on this data"

Output:
It seems that the Sweetviz package is not currently available for generating reports. However, I can help you with other types of analysis or provide insights using available tools. Would you like to proceed with a different type of analysis, like a summary or visualization of the dataset?

Tool Used: generate_sweetviz_report

Error:
Could not open report file: expected str, bytes or os.PathLike object, not NoneType

![Image](https://github.com/user-attachments/assets/9e11e20b-6901-49d4-a213-bff33f03bbef)
requirements.txt
`ai-data-science-team
streamlit
sqlalchemy
pandas
asyncio
langchain
langchain-openai
langgraph
openai
missingno
sweetviz
pytimetk
IPython`

dockerfile
`
FROM python:3.12
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 8501
CMD ["streamlit", "run", "app.py"]`

@mdancho84

**Comment by RawsthorneMat** [comment]
I have the exact same issue as the two above.   Some issue with modules passing to os paths?

**Comment by wildrewwildrew** [comment]
any ideas @mdancho84 ?

**Comment by mdancho84** [comment]
Was on vacation. Will be back at it soon. Catching up with my students but likely next week will be able to start working on this project.

**Comment by yunhui-shi** [comment]
pip install numpy==1.24 solves this issue

**Comment by mdancho84** [comment]
Can someone check this? 

``` bash
pip install numpy==1.24
```

**Comment by mdancho84** [comment]
[I just reran this example without issue.](https://github.com/business-science/ai-data-science-team/blob/master/examples/ds_agents/eda_tools_agent.ipynb) 

### Environment

This is my conda environment yaml:

``` yaml
name: ds4b_301p_dev
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - appnope=0.1.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - async-lru=2.0.4
  - blas=1.0
  - bleach=4.1.0
  - boost-cpp=1.82.0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.3.11
  - cairo=1.16.0
  - cffi=1.16.0
  - comm=0.2.1
  - contourpy=1.2.0
  - cycler=0.11.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - exceptiongroup=1.2.0
  - executing=0.8.3
  - expat=2.6.2
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - fonttools=4.25.0
  - freetype=2.12.1
  - fribidi=1.0.10
  - gdk-pixbuf=2.42.10
  - gettext=0.21.0
  - giflib=5.2.1
  - glib=2.78.4
  - glib-tools=2.78.4
  - graphite2=1.3.14
  - graphviz=2.50.0
  - gts=0.7.6
  - harfbuzz=4.3.0
  - icu=73.1
  - jedi=0.18.1
  - jinja2=3.1.3
  - jpeg=9e
  - json5=0.9.6
  - jsonschema-specifications=2023.7.1
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - jupyter_events=0.8.0
  - jupyter_server=2.10.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab_pygments=0.1.2
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.12
  - lerc=3.0
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.7.1
  - libcxx=14.0.6
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgd=2.3.3
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libglib=2.78.4
  - libiconv=1.16
  - libnghttp2=1.57.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - librsvg=2.54.4
  - libsodium=1.0.18
  - libssh2=1.11.0
  - libtiff=4.5.1
  - libtool=2.4.6
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.10.4
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib=3.8.0
  - matplotlib-base=3.8.0
  - matplotlib-inline=0.1.6
  - mistune=2.0.4
  - munkres=1.1.4
  - nbclient=0.8.0
  - nbconvert=7.10.0
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - notebook-shim=0.2.3
  - nspr=4.35
  - nss=3.89.1
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjdk=11.0.13
  - openjpeg=2.4.0
  - openssl=3.0.13
  - overrides=7.4.0
  - pandocfilters=1.5.0
  - pango=1.50.7
  - parso=0.8.3
  - pcre2=10.42
  - pexpect=4.8.0
  - pip=23.3.1
  - pixman=0.40.0
  - poppler=22.12.0
  - poppler-data=0.4.11
  - prompt_toolkit=3.0.43
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygraphviz=1.9
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.10.13
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - readline=8.2
  - referencing=0.30.2
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.6
  - scikit-learn=1.3.0
  - scipy=1.11.4
  - send2trash=1.8.2
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.41.2
  - stack_data=0.2.0
  - terminado=0.17.1
  - threadpoolctl=2.2.0
  - tinycss2=1.2.1
  - tk=8.6.12
  - tornado=6.3.3
  - traitlets=5.7.1
  - tzdata=2024a
  - urllib3=2.1.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.41.2
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - adjusttext==0.8
      - ai-data-science-team==0.0.0.9015
      - aiofiles==24.1.0
      - aiohttp==3.9.5
      - aiolimiter==1.2.0
      - aiosignal==1.3.1
      - aiosqlite==0.20.0
      - alabaster==1.0.0
      - alembic==1.14.0
      - altair==5.2.0
      - annotated-types==0.6.0
      - anthropic==0.40.0
      - antropy==0.1.6
      - anyio==4.6.2.post1
      - appdirs==1.4.4
      - arch==6.3.0
      - arrow==1.3.0
      - asgiref==3.7.2
      - assemblyai==0.35.1
      - astra-assistants==2.2.7
      - astrapy==1.5.2
      - async-timeout==4.0.3
      - asyncer==0.0.8
      - asyncio==3.4.3
      - atlassian-python-api==3.41.16
      - attrs==24.2.0
      - auth0-python==4.7.2
      - authlib==1.3.1
      - awscli==1.36.1
      - babel==2.17.0
      - backoff==2.2.1
      - backports-tarfile==1.2.0
      - bce-python-sdk==0.9.23
      - bcrypt==4.0.1
      - beautifulsoup4==4.12.3
      - blinker==1.9.0
      - boto3==1.36.5
      - botocore==1.36.5
      - build==1.1.1
      - cachetools==5.5.0
      - captcha==0.6.0
      - cassandra-driver==3.29.2
      - cassio==0.1.10
      - cattrs==24.1.2
      - certifi==2024.8.30
      - chardet==5.2.0
      - charset-normalizer==3.4.0
      - chatstream==0.0.1
      - chroma-hnswlib==0.7.6
      - chromadb==0.5.23
      - clevercsv==0.8.2
      - click==8.1.7
      - clickhouse-connect==0.7.19
      - cloudpickle==3.0.0
      - cohere==5.13.0
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - colorlog==6.9.0
      - composio-core==0.5.42
      - composio-langchain==0.5.42
      - coolname==2.2.0
      - crawl4ai==0.4.247
      - crewai==0.80.0
      - crewai-tools==0.14.0
      - cryptography==43.0.3
      - cython==3.0.12
      - databricks-sdk==0.40.0
      - dataclasses-json==0.6.4
      - datasets==3.1.0
      - deepdiff==8.0.1
      - deprecated==1.2.14
      - deprecation==2.1.0
      - dill==0.3.8
      - diskcache==5.6.3
      - distro==1.9.0
      - dnspython==2.7.0
      - docker==7.1.0
      - docstring-parser==0.16
      - docutils==0.21.2
      - docx2txt==0.8
      - dspy==2.5.41
      - dspy-ai==2.5.41
      - duckdb==1.1.3
      - duckduckgo-search==7.2.1
      - durationpy==0.9
      - e2b==1.0.4
      - e2b-code-interpreter==1.0.2
      - ecdsa==0.19.0
      - elastic-transport==8.15.1
      - elasticsearch==8.16.0
      - embedchain==0.1.125
      - emoji==2.14.0
      - et-xmlfile==2.0.0
      - events==0.5
      - extra-streamlit-components==0.1.71
      - faicons==0.2.2
      - faiss-cpu==1.9.0.post1
      - fake-http-header==0.3.5
      - fake-useragent==1.5.1
      - fastapi==0.115.5
      - fastapi-pagination==0.12.32
      - fastavro==1.9.7
      - filelock==3.16.1
      - filetype==1.2.0
      - firecrawl-py==1.6.1
      - flaml==2.3.2
      - flask==3.1.0
      - flatbuffers==24.3.7
      - fqdn==1.5.1
      - frozendict==2.4.4
      - frozenlist==1.4.1
      - fsspec==2024.3.1
      - future==1.0.0
      - geomet==0.2.1.post1
      - gitdb==4.0.11
      - gitingest==0.1.2
      - gitpython==3.1.43
      - google-ai-generativelanguage==0.6.10
      - google-api-core==2.17.1
      - google-api-python-client==2.154.0
      - google-auth==2.28.2
      - google-auth-httplib2==0.2.0
      - google-auth-oauthlib==1.2.1
      - google-cloud-aiplatform==1.73.0
      - google-cloud-bigquery==3.27.0
      - google-cloud-core==2.4.1
      - google-cloud-resource-manager==1.13.1
      - google-cloud-storage==2.18.2
      - google-crc32c==1.6.0
      - google-generativeai==0.8.3
      - google-resumable-media==2.7.2
      - google-search-results==2.4.2
      - googleapis-common-protos==1.63.0
      - gotrue==2.11.0
      - gptcache==0.1.44
      - grandalf==0.8
      - graphene==3.4.3
      - graphql-core==3.2.5
      - graphql-relay==3.2.0
      - greenlet==3.1.1
      - groq==0.5.0
      - grpc-google-iam-v1==0.13.1
      - grpcio==1.67.1
      - grpcio-health-checking==1.62.3
      - grpcio-status==1.62.3
      - grpcio-tools==1.62.3
      - gunicorn==23.0.0
      - h11==0.14.0
      - h2==4.1.0
      - h2o==3.46.0.1
      - holidays==0.33
      - hpack==4.0.0
      - html5lib==1.1
      - htmltools==0.5.1
      - httpcore==1.0.7
      - httplib2==0.22.0
      - httptools==0.6.4
      - httpx==0.28.1
      - httpx-sse==0.4.0
      - huggingface-hub==0.26.3
      - humanfriendly==10.0
      - hyperframe==6.0.1
      - idna==3.10
      - ijson==3.3.0
      - imageio==2.37.0
      - imagesize==1.4.1
      - importlib-metadata==6.11.0
      - importlib-resources==6.3.1
      - inflection==0.5.1
      - iniconfig==2.0.0
      - instructor==1.3.4
      - ipykernel==6.29.5
      - ipython==8.18.0
      - ipywidgets==8.1.2
      - isoduration==20.11.0
      - itk==5.4.2.post1
      - itk-core==5.4.2.post1
      - itk-filtering==5.4.2.post1
      - itk-io==5.4.2.post1
      - itk-numerics==5.4.2.post1
      - itk-registration==5.4.2.post1
      - itk-segmentation==5.4.2.post1
      - itsdangerous==2.2.0
      - jaraco-classes==3.4.0
      - jaraco-context==6.0.1
      - jaraco-functools==4.1.0
      - jiter==0.4.2
      - jmespath==1.0.1
      - joblib==1.4.2
      - jq==1.8.0
      - json-repair==0.30.2
      - jsonpatch==1.33
      - jsonpath-python==1.0.6
      - jsonpickle==4.0.0
      - jsonpointer==2.4
      - jsonref==1.1.0
      - jsonschema==4.23.0
      - jupyter==1.1.1
      - jupyter-console==6.6.3
      - jupyterlab==4.3.2
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.10
      - kaleido==0.2.1
      - keyring==25.5.0
      - kubernetes==31.0.0
      - lancedb==0.16.0
      - langchain==0.3.22
      - langchain-anthropic==0.3.0
      - langchain-astradb==0.5.2
      - langchain-aws==0.2.11
      - langchain-chroma==0.1.4
      - langchain-cohere==0.3.3
      - langchain-community==0.3.14
      - langchain-core==0.3.49
      - langchain-elasticsearch==0.3.0
      - langchain-experimental==0.3.3
      - langchain-google-calendar-tools==0.0.1
      - langchain-google-community==2.0.3
      - langchain-google-genai==2.0.6
      - langchain-google-vertexai==2.0.7
      - langchain-groq==0.2.1
      - langchain-milvus==0.1.7
      - langchain-mistralai==0.2.3
      - langchain-mongodb==0.2.0
      - langchain-nvidia-ai-endpoints==0.3.5
      - langchain-ollama==0.2.1
      - langchain-openai==0.3.11
      - langchain-pinecone==0.2.0
      - langchain-text-splitters==0.3.7
      - langchain-unstructured==0.1.5
      - langchainhub==0.1.20
      - langflow==1.1.1
      - langflow-base==0.1.1
      - langfuse==2.53.9
      - langgraph==0.3.22
      - langgraph-checkpoint==2.0.23
      - langgraph-prebuilt==0.1.7
      - langgraph-sdk==0.1.46
      - langgraph-supervisor==0.0.15
      - langsmith==0.1.138
      - langwatch==0.1.16
      - lark==1.2.2
      - lazy-loader==0.4
      - linkify-it-py==2.0.3
      - litellm==1.59.12
      - llvmlite==0.42.0
      - loguru==0.7.2
      - lsprotocol==2023.0.1
      - lxml==5.3.0
      - lz4==4.3.3
      - magicattr==0.1.6
      - mako==1.3.6
      - markdown==3.7
      - markdown-it-py==3.0.0
      - marshmallow==3.21.1
      - mdit-py-plugins==0.4.0
      - mdurl==0.1.2
      - mem0ai==0.1.34
      - mermaid==0.3.2
      - metal-sdk==2.5.1
      - metaphor-python==0.1.23
      - milvus-lite==2.4.10
      - missingno==0.5.2
      - mizani==0.9.3
      - mlflow==2.19.0
      - mlflow-skinny==2.19.0
      - mmh3==4.1.0
      - monotonic==1.6
      - more-itertools==10.5.0
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.0.5
      - multiprocess==0.70.16
      - multitasking==0.0.11
      - mypy-extensions==1.0.0
      - nanoid==2.0.0
      - nbsphinx==0.9.7
      - networkx==3.2.1
      - nh3==0.2.19
      - nltk==3.9.1
      - nodeenv==1.9.1
      - notebook==7.3.0
      - numba==0.59.0
      - oauthlib==3.2.2
      - ollama==0.4.4
      - onnxruntime==1.16.3
      - openai==1.70.0
      - openpyxl==3.1.5
      - opensearch-py==2.8.0
      - opentelemetry-api==1.27.0
      - opentelemetry-exporter-otlp-proto-common==1.27.0
      - opentelemetry-exporter-otlp-proto-grpc==1.27.0
      - opentelemetry-exporter-otlp-proto-http==1.27.0
      - opentelemetry-exporter-prometheus==0.48b0
      - opentelemetry-instrumentation==0.48b0
      - opentelemetry-instrumentation-asgi==0.48b0
      - opentelemetry-instrumentation-fastapi==0.48b0
      - opentelemetry-proto==1.27.0
      - opentelemetry-sdk==1.27.0
      - opentelemetry-semantic-conventions==0.48b0
      - opentelemetry-util-http==0.48b0
      - optuna==4.1.0
      - orderly-set==5.2.2
      - orjson==3.10.12
      - ormsgpack==1.9.1
      - outcome==1.3.0.post0
      - packaging==24.2
      - pandas==2.2.2
      - pandas-flavor==0.6.0
      - pandoc==2.4
      - parameterized==0.9.0
      - paramiko==3.5.0
      - passlib==1.7.4
      - pathos==0.3.2
      - patsy==0.5.6
      - pdfkit==1.0.0
      - peewee==3.17.6
      - pgvector==0.3.6
      - pillow==10.4.0
      - pinecone-client==5.0.1
      - pinecone-plugin-inference==1.1.0
      - pinecone-plugin-interface==0.0.7
      - pkginfo==1.12.0
      - platformdirs==4.3.6
      - playwright==1.49.1
      - plotly==5.20.0
      - plotnine==0.12.4
      - pluggy==1.5.0
      - plumbum==1.9.0
      - ply==3.11
      - polars==0.20.16
      - portalocker==2.10.1
      - postgrest==0.16.11
      - posthog==3.5.0
      - pox==0.3.4
      - ppft==1.7.6.8
      - primp==0.10.0
      - progressbar2==4.5.0
      - prometheus-client==0.21.0
      - prompt-toolkit==3.0.48
      - proto-plus==1.25.0
      - protobuf==4.25.3
      - psutil==6.1.1
      - pulsar-client==3.4.0
      - py==1.11.0
      - pyarrow==17.0.0
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pyautogen==0.4.1
      - pycryptodome==3.21.0
      - pydantic==2.10.3
      - pydantic-core==2.27.1
      - pydantic-settings==2.4.0
      - pydeck==0.8.1b0
      - pyee==12.0.0
      - pygments==2.19.1
      - pyjwt==2.10.0
      - pylance==0.19.2
      - pymilvus==2.5.0
      - pymongo==4.10.1
      - pynacl==1.5.0
      - pynrrd==1.1.3
      - pyopenssl==25.0.0
      - pypandoc==1.15
      - pypdf==5.1.0
      - pyperclip==1.9.0
      - pypika==0.48.9
      - pyproject-hooks==1.0.0
      - pyright==1.1.389
      - pysbd==0.3.4
      - pysher==1.0.8
      - pytest==8.3.4
      - python-docx==1.1.2
      - python-dotenv==1.0.1
      - python-jose==3.3.0
      - python-lsp-jsonrpc==1.1.2
      - python-multipart==0.0.19
      - python-utils==3.9.1
      - pytimetk==0.4.0
      - pytube==15.0.0
      - pytubefix==8.8.2
      - pytz==2024.2
      - pyvis==0.3.2
      - qdrant-client==1.9.2
      - qianfan==0.3.5
      - quarto==0.1.0
      - questionary==2.0.1
      - ragstack-ai-knowledge-store==0.2.1
      - rank-bm25==0.2.2
      - readme-renderer==44.0
      - realtime==1.0.6
      - redis==5.2.0
      - regex==2024.11.6
      - reportlab==4.2.0
      - requests==2.32.3
      - requests-oauthlib==1.4.0
      - requests-toolbelt==1.0.0
      - retry==0.9.2
      - rfc3986==2.0.0
      - rich==13.7.1
      - ridgeplot==0.1.24
      - rsa==4.7.2
      - ruff==0.8.1
      - s3transfer==0.11.2
      - safetensors==0.4.2
      - schema==0.7.7
      - scikit-image==0.25.2
      - seaborn==0.13.2
      - selenium==4.27.1
      - semver==3.0.2
      - sentence-transformers==2.5.1
      - sentry-sdk==2.19.0
      - setuptools==75.6.0
      - shap==0.46.0
      - shapely==2.0.6
      - shellingham==1.5.4
      - shiny==0.8.1
      - shinywidgets==0.3.1
      - simsimd==6.2.1
      - slicer==0.0.8
      - smmap==5.0.1
      - snowballstemmer==2.2.0
      - sortedcontainers==2.4.0
      - speechrecognition==3.10.4
      - sphinx==8.1.3
      - sphinx-gallery==0.3.1
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - spider-client==0.1.23
      - sqlalchemy==2.0.36
      - sqlite-vss==0.1.2
      - sqlmodel==0.0.18
      - sqlparse==0.5.3
      - starlette==0.41.3
      - statsmodels==0.14.1
      - stochastic==0.7.0
      - storage3==0.7.7
      - streamlit==1.40.1
      - streamlit-authenticator==0.4.1
      - strenum==0.4.15
      - supabase==2.6.0
      - supafunc==0.5.1
      - supersmoother==0.4
      - sweetviz==2.3.1
      - sympy==1.12
      - tabulate==0.9.0
      - tavily-python==0.5.0
      - tenacity==9.0.0
      - termcolor==2.5.0
      - tf-playwright-stealth==1.1.1
      - tifffile==2025.2.18
      - tiktoken==0.7.0
      - tokenizers==0.15.2
      - toml==0.10.2
      - tomli==2.2.1
      - tomli-w==1.1.0
      - toolz==0.12.1
      - torch==2.2.1
      - tqdm==4.67.1
      - transformers==4.38.2
      - tree-sitter==0.23.2
      - tree-sitter-python==0.23.4
      - trio==0.27.0
      - trio-websocket==0.11.1
      - tsfeatures==0.4.5
      - twine==6.0.1
      - typer==0.14.0
      - types-cachetools==5.5.0.20240820
      - types-python-dateutil==2.9.0.20241003
      - types-requests==2.32.0.20240712
      - typing-extensions==4.12.2
      - typing-inspect==0.9.0
      - uc-micro-py==1.0.3
      - ujson==5.10.0
      - uncurl==0.0.11
      - unstructured-client==0.25.9
      - upstash-vector==0.6.0
      - uri-template==1.3.0
      - uritemplate==4.1.1
      - uuid6==2024.7.10
      - uv==0.5.5
      - uvicorn==0.32.1
      - uvloop==0.19.0
      - validators==0.34.0
      - watchdog==4.0.0
      - watchfiles==0.21.0
      - weaviate-client==4.9.5
      - webcolors==24.11.1
      - websocket-client==1.8.0
      - websockets==12.0
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.10
      - wikipedia==1.4.0
      - wolframalpha==5.1.3
      - wrapt==1.16.0
      - wsproto==1.2.0
      - xarray==2023.10.1
      - xgboost==2.1.1
      - xlsxwriter==3.2.0
      - xmltodict==0.14.2
      - xxhash==3.5.0
      - yarl==1.9.4
      - yfinance==0.2.54
      - youtube-transcript-api==0.6.3
      - yt-dlp==2024.12.13
      - zep-python==2.0.2
      - zipp==3.18.1
      - zstandard==0.23.0
prefix: /Users/mdancho/opt/anaconda3/envs/ds4b_301p_dev
```
